---
kind: pipeline
type: ssh
name: default

concurrency:
  limit: 1

server:
  host:
    from_secret: server_address
  user: 
    from_secret: username
  ssh_key: 
    from_secret: ssh_key

platform:
  os: linux
  arch: amd64
   
steps:
- name: submodules
  image: alpine/git
  commands:
  - git submodule update --init --recursive
- name: build-install
  commands:
  - ./src/hst_autocompile.sh --hestia --install '~localsrc'
- name: bash-test
  commands:
  - bats ./test/test.bats
- name: php-test
  commands: 
  - ./test/check_php.sh

trigger:
  event: [ push ]

---
kind: pipeline
type: ssh
name: pull-request

concurrency:
      limit: 1

server:
  host:
    from_secret: server_address
  user: 
    from_secret: username
  ssh_key: 
    from_secret: ssh_key

platform:
      os: linux
      arch: amd64

steps:
- name: submodules
  image: alpine/git
  commands:
  - git submodule update --init --recursive
- name: build-install
  commands:
  - ./src/hst_autocompile.sh --hestia --install '~localsrc'
- name: bash-test
  commands:
  - bats ./test/test.bats
- name: php-test
  commands: 
  - ./test/check_php.sh

trigger:
  event: [ pull_request ]
---
kind: signature
hmac: 05165282c2f9b98afd11675dc98c99c4037d1672485eca49f462dc946c120a68